# Generated by Django 4.0.4 on 2022-06-23 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aviso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.IntegerField(max_length=100)),
                ('assunto', models.CharField(max_length=100)),
                ('data', models.DateField(max_length=100)),
            ],
        ),
    ]
